# Fill in <variables> with your actual grafana secrets
metrics:
  global:
    scrape_interval: 60s
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: <api_key>
            username: <metrics_username>
          url: <prom_url>

logs:
  configs:
  - name: default
    clients:
      - basic_auth:
          password: <api_key>
          username: <logs_username>
        url: <loki_url>
    positions:
      filename: /tmp/positions.yaml
    target_config:
      sync_period: 10s
    scrape_configs:
      - job_name: varlogs
        static_configs:
          - targets: [host.docker.internal]
            labels:
              instance: mc-server-v1-default
              job: varlogs
              __path__: /var/log/hostlog/*log
      - job_name: mclogs
        static_configs:
          - targets: [host.docker.internal]
            labels:
              instance: mc-server-v1-mclogs
              job: mclogs
              __path__: /var/log/mclogs/latest.log

integrations:
  node_exporter:
    enabled: true
    instance: mc-server-v1-default
  prometheus_remote_write:
    - basic_auth:
        password: <api_key>
        username: <metrics_username>
      url: <prom_url>
