- name: Install Grafana Agent
  hosts: all
  become: true

  vars:
    grafana_cloud_api_key: <api_key> # Example - glc_eyJrIjoiYjI3NjI5MGQxZTcyOTIxYTc0MDgzMGVhNDhlODNhYzA5OTk2Y2U5YiIsIm4iOiJhbnNpYmxldGVzdCIsImlkIjo2NTI5
    metrics_username: <metrics_username> # Example - 825019
    logs_username: <log_username> # Example - 411478
    prometheus_url: <prom_url> # Example - https://prometheus-us-central1.grafana.net/api/prom/push
    loki_url: <loki_url> # Example - https://logs-prod-017.grafana.net/loki/api/v1/push
  tasks:
    - name: Install Grafana Agent
      ansible.builtin.include_role:
        name: grafana.grafana.grafana_agent
      vars:
        grafana_agent_metrics_config:
          configs:
            - name: integrations
              remote_write:
                - basic_auth:
                    password: '{{ grafana_cloud_api_key }}'
                    username: '{{ metrics_username }}'
                  url: '{{ prometheus_url }}'

          global:
            scrape_interval: 60s
          wal_directory: /tmp/grafana-agent-wal
        grafana_agent_logs_config:
          configs:
            - name: default
              clients:
                - basic_auth:
                    password: '{{ grafana_cloud_api_key }}'
                    username: '{{ logs_username }}'
                  url: '{{ loki_url }}'
              positions:
                filename: /tmp/positions.yaml
              target_config:
                sync_period: 10s
              scrape_configs:
                - job_name: varlogs
                  static_configs:
                    - targets: [localhost]
                      labels:
                        instance: ${HOSTNAME:-default}
                        job: varlogs
                        __path__: /var/log/*log
                - job_name: mclogs
                  static_configs:
                    - targets: [localhost]
                      labels:
                      instance: ${HOSTNAME:-mclogs}
                      job: mclogs
                      __path__: /mnt/disks/gce-containers-mounts/tmpfss/mcdata/logs/*log
        grafana_agent_integrations_config:
          node_exporter:
            enabled: true
            instance: ${HOSTNAME:-default}
          prometheus_remote_write:
            - basic_auth:
                password: '{{ grafana_cloud_api_key }}'
                username: '{{ metrics_username }}'
              url: '{{ prometheus_url }}'
        grafana_agent_env_vars:
          HOSTNAME: '%H'
